import "./js/open-modal.js";
import "./js/header.js";
import "./js/google-dinosaur.js";
import "./js/our-command.js";
import "./js/footer-modal.js";
import "./js/biggest-number.js";
import "./js/calculator.js";
import "./js/time-calculator.js";
import "./js/leap-year.js";
import "./js/rock-scissors-paper.js";
import "./js/guess-number.js";
import "./js/dark-mode.js";
import "./js/choose-scientist.js";
import "./js/football.js";
import "./js/clicker.js";
import "./js/scrolltotop.js"
import "./js/footer.js"